version: '3.3'

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: tienda_frontend
    ports:
      - "3000:3000"
    volumes:
      # Hot-reload: monta todo el código
      - .:/app
      # Excluye node_modules del contenedor
      - /app/node_modules
      # Excluye .next del contenedor
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      # 👇 Carga las variables del archivo .env
      - NEXT_PUBLIC_BACKEND_HOST=${NEXT_PUBLIC_BACKEND_HOST}
    stdin_open: true
    tty: true